export default {
  ochre: "#FFDA53",
  darkOcher: "#9D852C",
  black: "#071018",
  blackLinks: "#333",
  offWhite: "#fafafa",
  offWhiteHover: "#E3D8D8",
  fontDisplay: "Tungsten",
  fontSubDisplay: "Tungsten",
  fontNav: "Tungsten",
  fontMain: "Sometype mono",
  fontFooter: "Tungsten",
  bold: "900",
  layoutMaxWidth: "1200px",
};
