export default {
  ochre: "#ffda53",
  darkOcher: "#9D852C",
  black: "#071018",
  blackLinks: "#151515", 
  offWhite: "#fafafa",
  offWhiteHover: "#E3D8D8",
  fontDisplay: "Tungsten",
  fontSubDisplay: "Tungsten",
  fontNav: "Share Tech Mono",
  fontMain: "Share Tech Mono",
  fontBlog: "Share",
  fontFooter: "Tungsten",
  bold: "bold",
  layoutMaxWidth: "1200px",
};
